# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.1-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev

      - run:
          name: "Setup custom environment variables"
          command: |
            echo 'export PHPCS_DIR=/tmp/phpcs' >> $BASH_ENV
            echo 'export SNIFFS_DIR=/tmp/sniffs' >> $BASH_ENV

      - run: git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
      - run: git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $SNIFFS_DIR

      - run: $PHPCS_DIR/bin/phpcs --config-set installed_paths $SNIFFS_DIR

      - run: $PHPCS_DIR/bin/phpcs -p . --standard=WordPress